language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm install
script:
  - npm run lint
# - npm run test:unit
# - npm run test:coveralls
  - npm run build
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=uzhlit/marugoto-frontend
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
env:
  global:
    - secure: BVIuDdhu3x476Sd2GNUgYk/9VgYz6SFKiBIcCbkuknqc6XaYl2EmaqT4OIXjU05r6LneH61ZL0CHtvUf/tlVPFjDnPq/b9EU6v1KECdH/UNRkH628SrN/joTuInJdXytjd/x+/MSCtRCdqVOuviwWWisDoUxVK/VwHLZM47L6G5agBXFoSF3hdJGtORAqwjz93YmddEvZ7n8TPajlxKzAVp1s+daH39mlIX6bSD3CkeHhggkRuIQKSRUu/Ek5sYFq4OaN8yRouGi5XvL0AmeGlg7QIg4u4fiXElGzquo80egTfIYcOMHnDTdzzuzktIfOVR3f1LNO5foWiXVHXWfhpIlIJJFaFXqlgegzJ4J/hMBZrV0Q5ulckHMQKQKP+G50xqTL7TZ/B7gLYsqnjugSzx7isLMe8KslweVU1Bv0S4q+Qi0RgCHulXdebTkEnnGKtfiFIOr0DzOyiNqSqOzl61RqevRT2absGNaraTvmrDM3oLjob5znxvg5xZXtO+2ldGXjXOdPpdgv2DyaVbb5/6cv3Dt4acUSwRlLBiqTaK1gqsUiuiiAfAZD5SktegHNVuY6lS7xh5Eh4PCAGKAoZK/3+IS5cTAvCbSpXTHuIitpTg7bmL71GTgN8C0xvuXxviwQJPMPxprCivsCA1AWU0qICOROJBUSqHtymJcIkU=
    - secure: ltsFLm7I8kG7W/U+kr6IcnVVzmo9DrSEuC7j3Duw8jpKFOl90NX/CBGBwuF1Ml8dhso9nnFsVut/VgjUfy89+k/tZ0Avc/Iicw6IyU6WL/Zxf7mPMpw06iosm0HcLWUzvwqIAdFLty40kgz4799s4PuO6XFUPd2ykNp9Vk6N/a6KrX50utMQL0tlZQpXPtv+7lmMk7Q6KnFMRAiq/ZKrik8uVWHPNPV2e2AxxQWB9OkfOoxbRVIO2iIda7NEtYRQrAtHRKpLKOPGpQCFHmjNUjz2ipKxMKZAhTkMn8Sgy0aWnLihWthhFnMqTjyBgyCcQ5dVF8SxHxBbpPzzfe6MJHviDHLbhwlwRk9lWulmOjgxwoZ6MVcfIUjVqhRk6o9eij/J3dMzgr1mujF7KR9h5tsWmfJgx35cADmCj7PH2o0kccrZFbxb8Lwj+zi8kpfFx1mRKq0Q09Rv7wxA9ZvgE0QoeRWnesG0KE5TcXjPmFpckBSPV4Co7sqkgOa7icwdMqh7oAk6Z14il+XNRqdlh9UiUxEBG2ES3E5zq24uoydkqbgEW7RbcPrhd8DH9KlyjUFW/OLCdnJd8SDBFHTD8eS+P6kojchpNRiynbX/VbB9tCFFZ7FrcIr+6b7hTtBTLYbrDfRRj8W9jbBYhxfX9YG+01fp7aR1eZmZUwM8H4w=
    - secure: VM4AOjC28XiGUVouyIG/+dIGmdxobFv3RvkOmUEpMS0KAeZWJatJxs3jsmvdN0XrQAYTYg0xn7MCxG9o7I64BUGVP1oqNJakDvw3jVFF5yuk1qHkzt6cGKZlE9BUJXnPmKKiLBfl0UnIBsOTZiVWRWmGfchAqzKN93EI6oLYsAuUbdmoI7ynZZPQTaxHPVGDX/1PJAF+jV3Z+uX9QLvL3iL7ZZi51+VZMUqvhfYp/dLgEKiVfPM9KnOb2fzGrESatxS5SGktoKjuECLEL//ddVRf44PD3T2igw1U0qazyZu9WiLlm1KDSu7naSzInNZZh+pJsszmc4LpXlM0D++mJtxhm8Pt0FZcImnqqMsBTvNHxjWARz8yYuvRxlT4xpmX4LLVleDy81+8v+0HWkv/9LgzapjPgfmOPr2gGozb2YTM5hLYn91Bt11M5eVbdqu9o7kNlbTfRLzsX78IIO7Y3gl7bFhejBTYkf7yR3IL2PcTkf0SVWROHPOuK9ZUXzn31JZW53n6RewwUdryWcPdjnGPD6QoK4QsOPm+1Kp9Gs5pDPgHzdtH4crwYBhv7Ifb/5J7kCdt8qbopziUTEIr34FvnPGoffSGz3LruRW4JAd+ElxEMQ3tmLfLsKjROg2SJamD2/cTptV1GUtj4YPLwCwNDB0DYWS1bqmD6GaNiag=
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: npm run deploy
#   on:
#     branch: master
